### ISSUE TITLE
user & password doesn't change

### ISSUE THREAD

**Issue by ssi-anik** [bitnami/bitnami-docker-cassandra#60]
My `docker-compose.yml` file is like below.
```yaml
version: '2'

services:
    cassandra:
        image:  bitnami/cassandra:3.11.5
        ports:
            - 9042:9042
        environment:
            - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
            - CASSANDRA_JMX_PORT_NUMBER=7199
            - CASSANDRA_CQL_PORT_NUMBER=9042
            - CASSANDRA_USER=root
            - CASSANDRA_PASSWORD=secret

```
According to the documentation, the user and password should be changed, if I am not wrong. But doesn't seem to work. Correct me if I am wrong.

![Screen Shot 2019-12-19 at 11 15 35 AM](https://user-images.githubusercontent.com/2676602/71146838-f9afd680-2250-11ea-8cdd-e28003e9c969.png)

TIA
