### ISSUE TITLE
Cassandra 3.11.5 cannot start

### ISSUE THREAD

**Issue by pratapagiri** [bitnami/bitnami-docker-cassandra#62]
**Description**

I have  used Cassandra 3.11.5 version and it cannot start and waits forever.

**Steps to reproduce the issue:**

1.  docker-compose up

**Describe the results you received:**

$ docker-compose up
Creating network "3_default" with the default driver
Creating volume "3_cassandra_data" with local driver
Creating cassandra ... done
Attaching to cassandra
cassandra    | cassandra 02:46:10.98
cassandra    | cassandra 02:46:10.98 Welcome to the Bitnami cassandra container
cassandra    | cassandra 02:46:10.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra    | cassandra 02:46:10.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra    | cassandra 02:46:10.98 Send us your feedback at containers@bitnami.com
cassandra    | cassandra 02:46:10.99
cassandra    | cassandra 02:46:10.99 INFO  ==> ** Starting Cassandra setup **
cassandra    | cassandra 02:46:11.00 INFO  ==> Validating settings in CASSANDRA_* env vars..
cassandra    | cassandra 02:46:11.00 WARN  ==> You set the environment variable CASSANDRA_PASSWORD=cassandra. This is the default value when bootstrapping Cassandra and should not be used in production environments.
cassandra    | cassandra 02:46:11.02 INFO  ==> Initializing Cassandra database...
cassandra    | cassandra 02:46:11.20 INFO  ==> Deploying Cassandra from scratch
cassandra    | cassandra 02:46:11.20 INFO  ==> Starting Cassandra
cassandra    | cassandra 02:46:11.20 INFO  ==> Checking that it started up correctly

**Describe the results you expected:**

Cassandra should start successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
version: '3.6'

services:
  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:3.11.5
    volumes:
        - ./cassandra_data:/bitnami
    environment:
        - CASSANDRA_USER=cassandra
        - CASSANDRA_PASSWORD=cassandra
        - CASSANDRA_CLUSTER_NAME=Testing
        - CASSANDRA_PASSWORD_SEEDER=yes
volumes:
  cassandra_data:
      driver: local
```

**Version**
Cassandra 3.11.5

- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 49
  Running: 49
  Paused: 0
  Stopped: 0
 Images: 70
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 15.39GiB
 Name: docker-desktop
 ID: 6LKL:XMCN:K63N:GEJA:M5G2:R5E2:JTNN:ZFT7:T3GL:E42I:DIXO:IYVJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 168
  Goroutines: 150
  System Time: 2020-02-09T02:58:04.4769975Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @pratapagiri, unfortunately I could not reproduce the issue with the docker-compose file you provided. Could you try this and check if you see more info?

```
version: '3.6'

services:
  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:3.11.5
    volumes:
        - ./cassandra_data:/bitnami
    environment:
        - CASSANDRA_USER=cassandra
        - CASSANDRA_PASSWORD=cassandra
        - CASSANDRA_CLUSTER_NAME=Testing
        - CASSANDRA_PASSWORD_SEEDER=yes
        - BITNAMI_DEBUG=1
volumes:
  cassandra_data:
      driver: local
```

(it basically adds the `BITNAMI_DEBUG` environment variable)

If you still don't find anything strange such as an entry not appearing, try this:

```
CASSANDRA_DATA=$(mktemp -d)
sudo chown 1001:1001 $CASSANDRA_DATA
docker run --rm --name cassandratest -v $CASSANDRA_DATA:/bitnami -e CASSANDRA_USER=cassandra -e CASSANDRA_PASSWORD=cassandra -e CASSANDRA_CLUSTER_NAME=Testing -e CASSANDRA_PASSWORD_SEEDER=yes -ti bitnami/cassandra:3.11.5 /bin/bash
```

Then, after entering the Cassandra shell, start Cassandra:

    /entrypoint.sh /run.sh

Once Cassandra exits with error or gets stuck, since the container won't exit, you can run the command below to see the Cassandra log in case there was any error:

    docker exec -ti cassandratest bash
    cat /opt/bitnami/cassandra/logs/cassandra_first_boot.log
